### PR TITLE
feat: update to use resvg 0.33.0

### PR DESCRIPTION
**Pull request by mfzl**
resvg did some major updates recently. This makes it compile with the newest version at this time.

The test images had only few pixel differences, probably due to changes in rendering. I've updated those images with very small differences.

### CODE REVIEW

**Comment by ssssota** [comment]
Thanks for your contribution!
I'll check it later.

**Comment by ssssota** [comment]
@mfzl Can you rebase the master branch?

**Comment by mfzl** [comment]
@ssssota done

**Comment by mfzl** [comment]
I've pushed the update, you can have a look. I'll revert if necessary

**Review by ssssota — APPROVED** [review]
LGTM
Once again, thank you!

**Pull request merged**
